// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mocks

import (
	"problem1/models"
	"sync"
)

// IUserServiceMock is a mock implementation of services.IUserService.
//
//	func TestSomethingThatUsesIUserService(t *testing.T) {
//
//		// make and configure a mocked services.IUserService
//		mockedIUserService := &IUserServiceMock{
//			GetFriendListFunc: func(userID int) ([]*models.User, error) {
//				panic("mock out the GetFriendList method")
//			},
//			GetFriendOfFriendListFunc: func(userID int) ([]*models.User, error) {
//				panic("mock out the GetFriendOfFriendList method")
//			},
//			GetFriendOfFriendListPagingFunc: func(userID int, page int, limit int) ([]*models.User, error) {
//				panic("mock out the GetFriendOfFriendListPaging method")
//			},
//		}
//
//		// use mockedIUserService in code that requires services.IUserService
//		// and then make assertions.
//
//	}
type IUserServiceMock struct {
	// GetFriendListFunc mocks the GetFriendList method.
	GetFriendListFunc func(userID int) ([]*models.User, error)

	// GetFriendOfFriendListFunc mocks the GetFriendOfFriendList method.
	GetFriendOfFriendListFunc func(userID int) ([]*models.User, error)

	// GetFriendOfFriendListPagingFunc mocks the GetFriendOfFriendListPaging method.
	GetFriendOfFriendListPagingFunc func(userID int, page int, limit int) ([]*models.User, error)

	// calls tracks calls to the methods.
	calls struct {
		// GetFriendList holds details about calls to the GetFriendList method.
		GetFriendList []struct {
			// UserID is the userID argument value.
			UserID int
		}
		// GetFriendOfFriendList holds details about calls to the GetFriendOfFriendList method.
		GetFriendOfFriendList []struct {
			// UserID is the userID argument value.
			UserID int
		}
		// GetFriendOfFriendListPaging holds details about calls to the GetFriendOfFriendListPaging method.
		GetFriendOfFriendListPaging []struct {
			// UserID is the userID argument value.
			UserID int
			// Page is the page argument value.
			Page int
			// Limit is the limit argument value.
			Limit int
		}
	}
	lockGetFriendList               sync.RWMutex
	lockGetFriendOfFriendList       sync.RWMutex
	lockGetFriendOfFriendListPaging sync.RWMutex
}

// GetFriendList calls GetFriendListFunc.
func (mock *IUserServiceMock) GetFriendList(userID int) ([]*models.User, error) {
	if mock.GetFriendListFunc == nil {
		panic("IUserServiceMock.GetFriendListFunc: method is nil but IUserService.GetFriendList was just called")
	}
	callInfo := struct {
		UserID int
	}{
		UserID: userID,
	}
	mock.lockGetFriendList.Lock()
	mock.calls.GetFriendList = append(mock.calls.GetFriendList, callInfo)
	mock.lockGetFriendList.Unlock()
	return mock.GetFriendListFunc(userID)
}

// GetFriendListCalls gets all the calls that were made to GetFriendList.
// Check the length with:
//
//	len(mockedIUserService.GetFriendListCalls())
func (mock *IUserServiceMock) GetFriendListCalls() []struct {
	UserID int
} {
	var calls []struct {
		UserID int
	}
	mock.lockGetFriendList.RLock()
	calls = mock.calls.GetFriendList
	mock.lockGetFriendList.RUnlock()
	return calls
}

// GetFriendOfFriendList calls GetFriendOfFriendListFunc.
func (mock *IUserServiceMock) GetFriendOfFriendList(userID int) ([]*models.User, error) {
	if mock.GetFriendOfFriendListFunc == nil {
		panic("IUserServiceMock.GetFriendOfFriendListFunc: method is nil but IUserService.GetFriendOfFriendList was just called")
	}
	callInfo := struct {
		UserID int
	}{
		UserID: userID,
	}
	mock.lockGetFriendOfFriendList.Lock()
	mock.calls.GetFriendOfFriendList = append(mock.calls.GetFriendOfFriendList, callInfo)
	mock.lockGetFriendOfFriendList.Unlock()
	return mock.GetFriendOfFriendListFunc(userID)
}

// GetFriendOfFriendListCalls gets all the calls that were made to GetFriendOfFriendList.
// Check the length with:
//
//	len(mockedIUserService.GetFriendOfFriendListCalls())
func (mock *IUserServiceMock) GetFriendOfFriendListCalls() []struct {
	UserID int
} {
	var calls []struct {
		UserID int
	}
	mock.lockGetFriendOfFriendList.RLock()
	calls = mock.calls.GetFriendOfFriendList
	mock.lockGetFriendOfFriendList.RUnlock()
	return calls
}

// GetFriendOfFriendListPaging calls GetFriendOfFriendListPagingFunc.
func (mock *IUserServiceMock) GetFriendOfFriendListPaging(userID int, page int, limit int) ([]*models.User, error) {
	if mock.GetFriendOfFriendListPagingFunc == nil {
		panic("IUserServiceMock.GetFriendOfFriendListPagingFunc: method is nil but IUserService.GetFriendOfFriendListPaging was just called")
	}
	callInfo := struct {
		UserID int
		Page   int
		Limit  int
	}{
		UserID: userID,
		Page:   page,
		Limit:  limit,
	}
	mock.lockGetFriendOfFriendListPaging.Lock()
	mock.calls.GetFriendOfFriendListPaging = append(mock.calls.GetFriendOfFriendListPaging, callInfo)
	mock.lockGetFriendOfFriendListPaging.Unlock()
	return mock.GetFriendOfFriendListPagingFunc(userID, page, limit)
}

// GetFriendOfFriendListPagingCalls gets all the calls that were made to GetFriendOfFriendListPaging.
// Check the length with:
//
//	len(mockedIUserService.GetFriendOfFriendListPagingCalls())
func (mock *IUserServiceMock) GetFriendOfFriendListPagingCalls() []struct {
	UserID int
	Page   int
	Limit  int
} {
	var calls []struct {
		UserID int
		Page   int
		Limit  int
	}
	mock.lockGetFriendOfFriendListPaging.RLock()
	calls = mock.calls.GetFriendOfFriendListPaging
	mock.lockGetFriendOfFriendListPaging.RUnlock()
	return calls
}
